### ISSUE TITLE
Inference time Multi GPUs for long video out of memory issue.

### ISSUE THREAD

**Issue by feiwu77777** [facebookresearch/co-tracker#51]
Hello, thanks a lot for sharing your work!

I used co-tracker for videos of up to 3min to track a segmentation mask, and the GPU from Colab ran out of memory. I understand I can reduce the grid size for the memory issue, but I wanted to know if it's possible to run the inference on multiple GPUs at the same time in parallel?

I'm not sure it would work as I would cut the video into 3 segments of 1min each and give the 3 segments to 3 GPUs for example. But I guess the tracking algorithm needs the whole video to work?

I saw in the colab notebook that you can track manually selected points, for my problem can I apply co-tracker on the first 1min of the video, save the tracked points of the last frame, and start tracking those points from minute 1 to minute 2?

**Comment by nikitakaraevv** [comment]
Hi @feiwu77777,
I think there's now a better solution to your problem. You can run CoTracker in online mode. This way, you don't have to keep the whole video in memory, only the current sliding window and estimated tracks. Please see https://github.com/facebookresearch/co-tracker?tab=readme-ov-file#online-mode and check out the [online demo](https://github.com/facebookresearch/co-tracker/blob/main/online_demo.py). 
Let me know if this helps!

**Comment by JamesSand** [comment]
> Hi @feiwu77777, I think there's now a better solution to your problem. You can run CoTracker in online mode. This way, you don't have to keep the whole video in memory, only the current sliding window and estimated tracks. Please see https://github.com/facebookresearch/co-tracker?tab=readme-ov-file#online-mode and check out the [online demo](https://github.com/facebookresearch/co-tracker/blob/main/online_demo.py). Let me know if this helps!

Thank you, that works for me!

**Comment by pvtoan** [comment]
Hi,

Thank you so much for sharing your interesting work!

At present, I am trying to understand about online_demo code. 

In particular, the variable "window_frames" will be appended continuously as long as new frames are fed.
Therefore, if I need to track points for several hours/days, "window_frames" will be very huge and might cause Out-of-memory.

In this case, is it possible if I discard previous frames and keep the number of frames in "window_frames" to be fixed, 
and the tracking accuracy is still OK?

**Comment by nikitakaraevv** [comment]
Hi @pvtoan, this variable exists for one reason - to make it possible to visualize the output using the existing tools in this repository. You can safely discard the previous frames.

**Comment by pvtoan** [comment]
Hi @nikitakaraevv,

Thank you for your clear answer.

Btw, when I already "discarded" previous frames of variable "window_frames" (it means the input of function "CoTrackerOnlinePredictor" has a fixed size)

However, the output including "pred_tracks" and "pred_visibility" are still appended continuously.

1. Could you please let me know which commands cause appending continuously for these two variables?
Also, is it safe too if I discard previous frames for these two variables?

2. Next, could you please roughly explain about the meaning of this command when returning values for these two variables in the last command of function "CoTrackerOnlinePredictor" (I just separate them for clearly view)?

pred_tracks = tracks * tracks.new_tensor([(W - 1) / (self.interp_shape[1] - 1), (H - 1) / (self.interp_shape[0] - 1),])

pred_visibility = visibilities > thr

**Comment by nikitakaraevv** [comment]
Hi @pvtoan, yes, this is done for the same reason, and we should probably fix it.
1. Here we continuously update tracks an visibilities inside the model in the online mode: 
https://github.com/facebookresearch/co-tracker/blob/0f9d32869ac51f3bd12c5ead9c206366cfb6caea/cotracker/models/core/cotracker/cotracker.py#L345
The fix is to do something like:
```
self.online_coords_predicted = coords_predicted[:, ind : ind + S]
self.online_vis_predicted = vis_predicted[:, ind : ind + S]
```
and make sure it doesn't break anything.

2. We resize each input video to the model resolution, and tracks are predicted in this resolution. This line transforms the predictions back to the original resolution.

**Comment by pvtoan** [comment]
Hi @nikitakaraevv ,

If you have time, please take a look at my issue.

Thank you for your help!

**Comment by nikitakaraevv** [comment]
Hi @pvtoan, this will take some time, I'll try to take a look over the weekend!

**Comment by Benedict-Cumberbatch-001** [comment]
> Hi @pvtoan, this will take some time, I'll try to take a look over the weekend!嗨，这需要一些时间，我会尽量在周末看看！
Hello, can the model use multiple GPUs when predicting? For example, I need to arrange multiple query points, which will cause a single GPU to be unable to meet the needs.

**Comment by Benedict-Cumberbatch-001** [comment]
> Hi @pvtoan, this will take some time, I'll try to take a look over the weekend!嗨，这需要一些时间，我会尽量在周末看看！

Hello, can the model use multiple GPUs when predicting? For example, I need to arrange a lot of query points, which will require a lot of video memory. A single GPU cannot meet such requirements.

**Comment by Benedict-Cumberbatch-001** [comment]
> Hi @pvtoan, this will take some time, I'll try to take a look over the weekend!

Hello, may I ask if the model can use multiple GPUs during inference? For example, I need to configure many query points, which will consume a large amount of GPU memory. A single GPU cannot meet such requirements.

**Comment by ohjunseok3089** [comment]
@holdrainxu Did you figure out how to use multiple GPU in parallel?

**Comment by holdrainxu** [comment]
> [@holdrainxu](https://github.com/holdrainxu) Did you figure out how to use multiple GPU in parallel?

Not yet, but I think the online mode can alleviate this problem.

**Comment by ohjunseok3089** [comment]
@holdrainxu Agree, but I want to use the seg_mask and seems like that is only supported from offline mode TT

**Comment by holdrainxu** [comment]
> [@holdrainxu](https://github.com/holdrainxu) Agree, but I want to use the seg_mask and seems like that is only supported from offline mode TT

Regrettably, if you have any clues, we can discuss it.
